CREATE TABLE `fiel` (
`id_fiel` INT NOT NULL AUTO_INCREMENT COMMENT 'Código do Fiel',
`nome_fiel` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Nome do Fiel',
`sobrenome_fiel` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Sobrenome do Fiel',
`data_nascimento_fiel` DATETIME NOT NULL COMMENT 'Data de Nascimento do Fiel',
`genero_fiel` CHAR(1) NULL DEFAULT NULL COMMENT 'Genero do Fiel (M/F)',
`rg_fiel` INT NOT NULL COMMENT 'RG do Fiel',
`cpf_fiel` INT NOT NULL COMMENT 'CPF do Fiel',
`tel_residencial_fiel` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Telefone Residencial do Fiel',
`tel_comercial_fiel` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Telefone Comercial do Fiel',
`ramal_fiel` INT NOT NULL COMMENT 'Ramal do Fiel',
`tel_celular_fiel` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Telefone Celular do Fiel',
`data_falecimento_fiel` DATETIME NOT NULL COMMENT 'Data de Falecimento do Fiel',
`id_profissao_fiel` INT NOT NULL COMMENT 'Código da Frofissao do Fiel',
`email_fiel` VARCHAR(30) NULL DEFAULT NULL COMMENT 'E-mail do Fiel',
`data_conversao_fiel` DATETIME NULL COMMENT 'Data de Conversão do Fiel',
`padrinho_madrinha_fiel` VARCHAR(30) NULL DEFAULT NULL COMMENT 'Padrinho ou Madrinha do Fiel',
`data_desligamento_fiel` DATETIME NOT NULL COMMENT 'Data de Desligamento do Fiel',
`situacao_fiel` CHAR(1) NULL DEFAULT NULL COMMENT 'Situação do Fiel (A/I)',
PRIMARY KEY (`id_fiel`) COMMENT 'Código do Fiel');