CREATE TABLE `templo` ( 
`id_templo` INT NOT NULL AUTO_INCREMENT COMMENT 'Código do Templo', 
`nome_templo` VARCHAR(30) NOT NULL COMMENT 'Nome do Templo',
`situacao_templo` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'Situação do Templo (A/I)', 
`cnpj_templo` VARCHAR(14) NULL DEFAULT NULL COMMENT 'CNPJ do Templo',
`email_templo` VARCHAR(30) NOT NULL COMMENT 'Email do Templo',
`telefone_templo` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Telefone do Templo',
`ramal_templo` int NULL DEFAULT NULL COMMENT 'Ramal do Templo',
`fax_templo` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Fax do Templo',
`matriz_templo` CHAR(1) NOT NULL DEFAULT 'M' COMMENT 'Situação do Templo (M/F)', 
`endereco_templo` VARCHAR(30) NOT NULL COMMENT 'Endereco do Templo',
`numero_templo` int NULL DEFAULT NULL COMMENT 'Número do Templo',
`complemento_templo` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Complemento do Templo',
`bairro_templo` VARCHAR(30) NOT NULL COMMENT 'Bairro do Templo',
`cidade_templo` VARCHAR(40) NOT NULL COMMENT 'Cidade do Templo',
`uf_templo` CHAR(2) NOT NULL COMMENT 'Estado do Templo',
`cep_templo` CHAR(10) NOT NULL COMMENT 'CEP do Templo',
`cx_postal_templo` CHAR(10) NOT NULL COMMENT 'Caixa Postal do Templo',
PRIMARY KEY (`id_templo`) COMMENT 'Código do Templo', 
INDEX `idx_nm_templo` (`nome_templo`(30)) COMMENT 'Nome do Templo' ) ENGINE = MyISAM COMMENT = 'Armazena os nomes dos Templos';