INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('AC','Acre','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('AL','Alagoas','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('AP','Amapá','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('AM','Amazonas','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('BA','Bahia','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('CE','Ceará','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('DF','Distrito Federal','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('ES','Espírito Santo','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('GO','Goiás','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('MA','Maranhão','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('MT','Mato Grosso','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('MS','Mato Grosso do Sul','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('MG','Minas Gerais','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('PA','Pará','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('PB','Paraíba','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('PR','Paraná','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('PE','Pernambuco','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('PI','Piauí','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('RJ','Rio de Janeiro','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('RN','Rio Grande do Norte','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('RS','Rio Grande do Sul','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('RO','Rondônia','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('RR','Roraima','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('SC','Santa Catarina','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('SP','São Paulo','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('SE','Sergipe','A');
INSERT INTO `estado`(`estado`, `nome_estado`, `situacao_estado`) values('TO','Tocantins','A');